### PR TITLE
Allow additional args to headless-build.sh

### PR DESCRIPTION
**Pull request by addshore**
This allows passing in extra defines etc when
used via github actions

### CODE REVIEW

**Comment by addshore** [comment]
Not actually sure how to make this accessible via the action as of yet

**Comment by xanderhendriks** [comment]
Can you give an example of how you can add defines this way? I can't find any information on command line parameters for the headless-build.sh script.
If it is just for adding defines then you can do that this way:

- Add environment variables in your [workflow](https://github.com/xanderhendriks/stm32-sample-application/blob/master/.github/workflows/continuous_integration_pipeline.yml#L74)
- Add [makefile.defs](https://github.com/xanderhendriks/stm32-sample-application/blob/master/applications/sample_application/targets/STM32/makefile.defs) with a mapping from the environment variables to make variables
- Add the mapping from the make variables to the code defines in the project:
image

**Comment by addshore** [comment]
Thanks for the notes @xanderhendriks 
I'll give the [makefile.defs](https://github.com/xanderhendriks/stm32-sample-application/blob/master/applications/sample_application/targets/STM32/makefile.defs) file approach a go and see if that works for me.

Regarding the `-D`, ultimately headless build just calls `stm32cubeide` with some options.

```
user@b09ee309959f:/# cat /opt/st/stm32cubeide_1.15.0/headless-build.sh
#!/bin/bash

basedir=$(dirname "$BASH_SOURCE")
"$basedir"/stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild "$@"
```

I found at https://community.st.com/t5/stm32cubeide-mcus/how-do-i-build-my-stm32cubeide-code-via-the-command-line-on/td-p/112919 how to get the help text from `stm32cubeide` for CLI args

```
Usage: /opt/st/stm32cubeide_1.15.0/stm32cubeide -data <workspace> -application org.eclipse.cdt.managedbuilder.core.headlessbuild [ OPTIONS ]

   -data       {/path/to/workspace}
   -remove     {[uri:/]/path/to/project}
   -removeAll  {[uri:/]/path/to/projectTreeURI} Remove all projects under URI
   -import     {[uri:/]/path/to/project}
   -importAll  {[uri:/]/path/to/projectTreeURI} Import all projects under URI
   -build      {project_name_reg_ex{/config_reg_ex} | all}
   -cleanBuild {project_name_reg_ex{/config_reg_ex} | all}
   -markerType Marker types to fail build on {all | cdt | marker_id}
   -no-indexer Disable indexer
   -verbose    Verbose progress monitor updates
   -printErrorMarkers Print all error markers
   -I          {include_path} additional include_path to add to tools
   -include    {include_file} additional include_file to pass to tools
   -D          {prepoc_define} addition preprocessor defines to pass to the tools
   -E          {var=value} replace/add value to environment variable when running all tools
   -Ea         {var=value} append value to environment variable when running all tools
   -Ep         {var=value} prepend value to environment variable when running all tools
   -Er         {var} remove/unset the given environment variable
   -T          {toolid} {optionid=value} replace a tool option value in each configuration built
   -Ta         {toolid} {optionid=value} append to a tool option value in each configuration built
   -Tp         {toolid} {optionid=value} prepend to a tool option value in each configuration built
   -Tr         {toolid} {optionid=value} remove a tool option value in each configuration built
               Tool option values are parsed as a string, comma separated list of strings or a boolean based on the options type
               ```

**Comment by xanderhendriks** [comment]
@addshore did the makefile.defs work for you? Otherwise I'm happy to merge in your proposed change provided you update the readme to include the documenation you provided above and add an example of how to use it here: https://github.com/xanderhendriks/stm32-sample-application
That way other people can benefit from the change as well.

**Comment by addshore** [comment]
I havn't given `makefile.defs` a go yet!
But I'll be sure to report back when I get around to a next iteration and attempt on this!

**Comment by xanderhendriks** [comment]
Closing this one for now as there his been no action to get the sample code working. I am happy to maintain this for the community and to merge in changes from the community. But to keep these changes useful for the community I do expect at least a sample to be shared of how to use this change. Happy for that to be a pull request to the above mentioned [sample application](https://github.com/xanderhendriks/stm32-sample-application)

**Comment by addshore** [comment]
I'll get back around to this at some stage, but probably not until I need to touch this topic again, currently my fork is working well etc

**Pull request closed without merging**
